# This is a basic workflow to help you get started with Actions

name: git workflow watch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  
  workflow_dispatch:
jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:
        - uses: actions/checkout@v2
      
        - name: Initialize Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pika
        - name: reset          
          run: python actionhelper.py dial_0
          env:
           AMQP_URL: ${{ secrets.AMQP_URL }}            
        - name: Sleep for 10s
          uses: juliangruber/sleep-action@v1
          with:
            time: 10s
        
        - name: getting data          
          run: python actionhelper.py dial_30
          env:
           AMQP_URL: ${{ secrets.AMQP_URL }}
           
        - name: Sleep for 10s
          uses: juliangruber/sleep-action@v1
          with:
            time: 10s           
           
        - name: building          
          run: python actionhelper.py dial_60
          env:
           AMQP_URL: ${{ secrets.AMQP_URL }}
           
        - name: Sleep for 10s
          uses: juliangruber/sleep-action@v1
          with:
            time: 10s           
           
        - name: deploying         
          run: python actionhelper.py dial_90
          env:
           AMQP_URL: ${{ secrets.AMQP_URL }}
           
        - name: Sleep for 10s
          uses: juliangruber/sleep-action@v1
          with:
            time: 10s           
        - name: success          
          run: python actionhelper.py dial_145
          env:
           AMQP_URL: ${{ secrets.AMQP_URL }}
           
        - name: Sleep for 10s
          uses: juliangruber/sleep-action@v1
          with:
            time: 10s     
            
        - name: fail          
          run: python actionhelper.py dial_160
          env:
           AMQP_URL: ${{ secrets.AMQP_URL }}
           
        - name: Sleep for 10s
          uses: juliangruber/sleep-action@v1
          with:
            time: 10s                 
                        
